version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - 'tmp'
  deploy-prod:
    executor:
      name: node/default
    steps:            
      - run: mkdir tmp && zip -r tmp/dist.zip dist
      - run:
          name: Installing deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install --upgrade setuptools
            sudo pip3 install awsebcli --upgrade
      - attach_workspace:
          at: .
      - run:
          name: Deploying
          command: eb deploy GuesserApi-env

workflows:
  deploy-prod:
    jobs:
      - build
      - deploy-prod:
          context: guesser-api
          filters:
            branches:
              only:
                - circleci-project-setup
          requires:
            - build
          